---
  server:
    port: 9128
  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/flow-track
      username: postgres
      password: root
      dialect: org.hibernate.dialect.PostgreSQLDialect
    jpa:
      hibernate:
        ddl-auto: update
